#!/bin/bash

LC_NUMBER=$1
LC_TITLE=$2
SNAKE_CASE=$(echo $2 | sed -e 's/\([A-Z][a-z]*\)/_\1/g' | \
  sed -e 's/^_//' | tr [:lower:] [:upper:])

echo "Spinning up new cpp sandbox in directory:"
echo "    `pwd`/$LC_TITLE/"

# Make the directories and cd into it
mkdir "$LC_NUMBER-$LC_TITLE"
CPP="$LC_NUMBER-$LC_TITLE/cpp"
mkdir "$CPP"
cd $CPP

# C++ Header
printf "\
#ifndef $SNAKE_CASE
#define $SNAKE_CASE

class $LC_TITLE {
  public:
    
  private:
};

#endif

" > $LC_TITLE.h

# C++ Implementation file
printf "#include \"$LC_TITLE.h\"\n" > $LC_TITLE.cpp

# C++ Test file containing main
printf "\
#include \"$LC_TITLE.h\"
#include <iostream>
#include <cassert>

int main() {
  $LC_TITLE soln;
}

" > test.cpp

# Makefile
printf "\
$LC_TITLE:
\tg++ $LC_TITLE.h $LC_TITLE.cpp test.cpp -o run

clean:
\trm -rf run

" > makefile

vim $LC_TITLE.h +"vsp $LC_TITLE.cpp" +"wincmd h" +"sp test.cpp" \
    +"wincmd k" +mks +wa +"startinsert!"

