#!/bin/bash

LC_NUMBER=$1
LC_TITLE=$2
SNAKE_CASE=$(echo TestCodeHere | sed -e 's/\([A-Z][a-z]*\)/_\1/g' | \
  sed -e 's/^_//' | tr [:lower:] [:upper:])

echo "Spinning up new cpp sandbox in directory:"
echo "    `pwd`/$LC_TITLE/"

mkdir "$LC_NUMBER-$LC_TITLE"
CPP="$LC_NUMBER-$LC_TITLE/cpp"
mkdir "$CPP"

printf "#ifndef $SNAKE_CASE\n#define $SNAKE_CASE\n\n#endif\n\n" > $CPP/$LC_TITLE.h
printf "#include \"$LC_TITLE.h\"\n\n" > $CPP/$LC_TITLE.cpp
printf "#include \"$LC_TITLE.h\"\n\nint main() {\n    \n}\n\n" > $CPP/test.cpp
printf "$LC_TITLE:\n\tg++ $LC_TITLE.h $LC_TITLE.cpp test.cpp -o run\n\nclean:\n\trm -rf run\n\n"\
    > $CPP/makefile

